name: Validace a Preprocessing nově přidaných SQL her
on:
  pull_request_target:
    paths:
      - 'src/data/games/**'
      - 'public/assets/**'
      - 'public/pageAssets/**'
    branches:
      - main

jobs:
  validate-and-commit:
    if: startsWith(github.event.pull_request.head.ref, 'feature/add-game-')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout důvěryhodného kódu
        uses: actions/checkout@v4
        with:
          sparse-checkout:  |
            src/scripts/validate_game.py
          path: trusted-code

      - name: Checkout PR kódu
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          path: pr-data
          fetch-depth: 0

      - name: Kontrola nepovolených změn
        run: |
          cd pr-data
          git fetch origin ${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only remotes/origin/${{ github.base_ref }}...HEAD)
          
          for file in $CHANGED_FILES; do
            if [[ ! $file =~ ^src/data/games/.*\.json$ ]] && \
               [[ ! $file =~ ^public/assets/.* ]] && \
               [[ ! $file =~ ^public/pageAssets/.* ]]; then
              echo "::error::Nepovolená změna! Soubor '$file' není povolen."
              exit 1
            fi
          done

      - name: Nastavení Pythonu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Spuštění validátoru (Python)
        run: python trusted-code/src/scripts/validate_game.py --path pr-data

      - name: Commit a Push změn (Preprocessing)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: automatický preprocessing nové hry [skip ci]"
          repository: pr-data
          file_pattern: 'src/data/games/*.json'
